<?php

namespace Database\Seeders;

use App\Models\DiscountCode;
use App\Models\ShippingCost;
use App\Models\User;
use App\Models\Product;
use App\Models\ProductCopy;
use Illuminate\Support\Str;
use App\Models\ProductCategory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    protected static ?string $password;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // Maak users aan
        User::create([
            'first_name' => 'Bilal',
            'last_name' => 'van Loon',
            'email' => 'bilalvanloon@gmail.com',
            'role' => 'admin',
            'password' => static::$password ??= Hash::make('12345678'),
        ]);

        User::create([
            'first_name' => 'Pascal',
            'last_name' => 'van Loon',
            'email' => 'vanloon_1983@hotmail.com',
            'role' => 'user',
            'password' => static::$password ??= Hash::make('12345678'),
        ]);

        User::create([
            'first_name' => 'Soner',
            'last_name' => 'Altin',
            'email' => 'dogus2011@gmail.com',
            'role' => 'admin',
            'password' => static::$password ??= Hash::make('12345678'),
        ]);

        User::create([
            'first_name' => 'Delil',
            'last_name' => 'Tas',
            'email' => 'deliltass14@gmail.com',
            'role' => 'admin',
            'password' => static::$password ??= Hash::make('12345678'),
        ]);

        User::create([
            'first_name' => 'Cemal',
            'last_name' => 'Tas',
            'email' => 'cemaltasct@gmail.com',
            'role' => 'admin',
            'password' => static::$password ??= Hash::make('12345678'),
        ]);

        User::create([
            'first_name' => 'Orhan',
            'last_name' => 'Calik',
            'email' => 'fenafinnursaid@gmail.com',
            'role' => 'admin',
            'password' => static::$password ??= Hash::make('12345678'),
        ]);

        ShippingCost::create([
            'amount' => 2.50,
            'country' => 'NL',
            'is_published' => 1,
            'created_by' => 1
        ]);

        ShippingCost::create([
            'amount' => 7.50,
            'country' => 'BE',
            'is_published' => 1,
            'created_by' => 1
        ]);

        DiscountCode::create([
            'code' => 'afhalen-nl',
            'discount_type' => 'amount',
            'discount' => 2.50,
            'is_published' => 1,
        ]);

        DiscountCode::create([
            'code' => 'afhalen-be',
            'discount_type' => 'amount',
            'discount' => 7.50,
            'is_published' => 1,
        ]);

        $category = ProductCategory::create([
              'name' => 'Risale-i Nur',
              'slug' => Str::slug('Risale-i Nur'),
              'created_by' => '1',
              'updated_by' => '1',
              'is_published' => '1'
          ]);

        // Nederlands
        $nlCopy = ProductCopy::create([
            'name' => 'Nederlands',
            'is_published' => 1,
            'created_by' => 1,
            'updated_by' => 1,
        ]);

        // Nederlands-Turks
        $nlTrCopy = ProductCopy::create([
            'name' => 'Nederlands-Turks',
            'is_published' => 1,
            'created_by' => 1,
            'updated_by' => 1,
        ]);

        // Engels
        $enCopy = ProductCopy::create([
            'name' => 'Engels',
            'is_published' => 1,
            'created_by' => 1,
            'updated_by' => 1,
        ]);

        // Engels-Turks
        $enTrCopy = ProductCopy::create([
            'name' => 'Engels-Turks',
            'is_published' => 1,
            'created_by' => 1,
            'updated_by' => 1,
        ]);

  $books = [
          [
            'title' => 'Afwegingen van Geloof & Ongeloof - Nederlands',
            'slug' => Str::slug('Afwegingen van Geloof & Ongeloof - Nederlands'),
            'short_description' => 'In dit boek wordt het verschil tussen de waarnemingen en vruchten van een gelovige visie en een ongelovige visie behandeld. Zodoende wordt de lezer in staat gesteld om af te wegen welke weg beter voor hem is. De logische, rationele en feitelijke bevindingen in dit boek maken duidelijk dat de ene visie op aarde al helse folteringen veroorzaakt, terwijl de andere visie op aarde al paradijselijke geneugten oplevert. Een objectieve lezer zal ervaren dat dit boek zal bijdragen aan het scherpstellen van zijn levensbeschouwing.',
            'long_description' => '',
            'price' => 15.00,
            'is_published' => 1,
            'product_copy_id' => $nlCopy->id,
            'stock' => 100,
            'image_1' => 'images/books/afwegingen/afwegingen_nl_front_2.png',
            'image_2' => 'images/books/afwegingen/afwegingen_nl_inside.webp',
            'pdf_file' => 'pdfs/afwegingen.pdf',
            'online_lezen_image' => 'images/books/leesbuttons/lees_afwegingen_btn.png',
            'seo_description' => '',
            'seo_tags' => ['Risale-i Nur', 'Islam', 'Geloof', "Qur'an"],
            'seo_author' => 'Said Nursi',
            'seo_robots' => 'noindex, nofollow',
            'seo_canonical_url' => '',
            'weight' => 409,
            'height' => 20,
            'width' => 14,
            'depth' => 2,
            'pages' => 0,
            'binding_type' => 'Hardcover',
            'ean_code' => '',
            'created_by' => 1,
            'updated_by' => 1,
          ],
          [
              'title' => 'Afwegingen van Geloof & Ongeloof - Nederlands-Turks',
              'slug' => Str::slug('Afwegingen van Geloof & Ongeloof - Nederlands-Turks'),
              'short_description' => 'In dit boek wordt het verschil tussen de waarnemingen en vruchten van een gelovige visie en een ongelovige visie behandeld. Zodoende wordt de lezer in staat gesteld om af te wegen welke weg beter voor hem is. De logische, rationele en feitelijke bevindingen in dit boek maken duidelijk dat de ene visie op aarde al helse folteringen veroorzaakt, terwijl de andere visie op aarde al paradijselijke geneugten oplevert. Een objectieve lezer zal ervaren dat dit boek zal bijdragen aan het scherpstellen van zijn levensbeschouwing.',
              'long_description' => '',
              'price' => 20.00,
              'is_published' => 1,
              'product_copy_id' => $nlTrCopy->id,
              'stock' => 100,
              'image_1' => 'images/books/afwegingen/afwegingen_nl-tr_front_3.png',
              'image_2' => 'images/books/afwegingen/afwegingen_nl-tr_inside.webp',
              'image_3' => 'images/books/afwegingen/afwegingen_nl-tr_case.webp',
              'seo_description' => '',
              'seo_tags' => ['Risale-i Nur', 'Islam', 'Geloof', "Qur'an"],
              'seo_author' => 'Said Nursi',
              'seo_robots' => 'noindex, nofollow',
              'seo_canonical_url' => '',
              'weight' => 800,
              'height' => 21,
              'width' => 14.5,
              'depth' => 4,
              'pages' => 0,
              'binding_type' => 'Hardcover',
              'ean_code' => '',
              'created_by' => 1,
              'updated_by' => 1,
          ],
          [
              'title' => 'Broederschap en Oprechtheid - Nederlands',
              'slug' => Str::slug('Broederschap en Oprechtheid - Nederlands'),
              'short_description' => 'Dit boek beschrijft hoe Islamitische broederschap en oprechtheid in de huidige tijden kunnen worden betracht. Oorzaken die broederschap en oprechtheid ondermijnen worden uiteengezet, waarnaast Qur’anische principes worden omschreven die resulteren in de totstandbrenging en handhaving van ware Islamitische broederschap en oprechtheid.',
              'long_description' => '',
              'price' => 7.50,
              'is_published' => 1,
              'product_copy_id' => $nlCopy->id,
              'stock' => 100,
              'image_1' => 'images/books/broederschap/broederschap_nl_front.webp',
              'image_2' => 'images/books/broederschap/broederschap_nl_inside.webp',
              'pdf_file' => 'pdfs/broederschap.pdf',
              'online_lezen_image' => 'images/books/leesbuttons/lees_broederschap_btn.png',
              'seo_description' => '',
              'seo_tags' => ['Risale-i Nur', 'Islam', 'Geloof', "Qur'an"],
              'seo_author' => 'Said Nursi',
              'seo_robots' => 'noindex, nofollow',
              'seo_canonical_url' => '',
              'weight' => 180,
              'height' => 18.8,
              'width' => 11.7,
              'depth' => 1.5,
              'pages' => 0,
              'binding_type' => 'Hardcover',
              'ean_code' => '',
              'created_by' => 1,
              'updated_by' => 1,
          ],
          [
              'title' => 'Broederschap en Oprechtheid - Nederlands-Turks',
              'slug' => Str::slug('Broederschap en Oprechtheid - Nederlands-Turks'),
              'short_description' => 'Dit boek beschrijft hoe Islamitische broederschap en oprechtheid in de huidige tijden kunnen worden betracht. Oorzaken die broederschap en oprechtheid ondermijnen worden uiteengezet, waarnaast Qur’anische principes worden omschreven die resulteren in de totstandbrenging en handhaving van ware Islamitische broederschap en oprechtheid.',
              'long_description' => '',
              'price' => 12.50,
              'is_published' => 1,
              'product_copy_id' => $nlTrCopy->id,
              'stock' => 100,
              'image_1' => 'images/books/broederschap/broederschap_nl-tr_front.webp',
              'image_2' => 'images/books/broederschap/broederschap_nl-tr_inside.webp',
              'seo_description' => '',
              'seo_tags' => ['Risale-i Nur', 'Islam', 'Geloof', "Qur'an"],
              'seo_author' => 'Said Nursi',
              'seo_robots' => 'noindex, nofollow',
              'seo_canonical_url' => '',
              'weight' => 370,
              'height' => 18.8,
              'width' => 11.7,
              'depth' => 2.3,
              'pages' => 0,
              'binding_type' => 'Hardcover',
              'ean_code' => '',
              'created_by' => 1,
              'updated_by' => 1,
          ],
          [
              'title' => 'Geloofswaarheden',
              'slug' => Str::slug('Geloofswaarheden'),
              'short_description' => 'In dit boek worden verscheidene geloofskwesties behandeld. Waarheden achter bepaalde Islamitische geloofsfundamenten worden verhelderd, waaronder de wijsheid achter de dagelijkse vijf tijdstippen van de geboden gebeden en de wijsheid achter de schepping van de duivel. Dit boek zal voor de lezer vele controversiële punten ontwarren.',
              'long_description' => '',
              'price' => 5.00,
              'is_published' => 1,
              'product_copy_id' => $nlCopy->id,
              'stock' => 100,
              'image_1' => 'images/books/geloofswaarheden/geloofswaarheden-nl-front.webp',
              'image_2' => 'images/books/geloofswaarheden/geloofswaarheden-nl-inside.webp',
              'pdf_file' => 'pdfs/geloofswaarheden.pdf',
              'online_lezen_image' => 'images/books/leesbuttons/lees_geloofswaarheden_btn.png',
              'seo_description' => '',
              'seo_tags' => ['Risale-i Nur', 'Islam', 'Geloof', "Qur'an"],
              'seo_author' => 'Said Nursi',
              'seo_robots' => 'noindex, nofollow',
              'seo_canonical_url' => '',
              'weight' => 0,
              'height' => 0,
              'width' => 0,
              'depth' => 0,
              'pages' => 0,
              'binding_type' => 'Softcover',
              'ean_code' => '',
              'created_by' => 1,
              'updated_by' => 1,
          ],
          [
              'title' => 'Het Traktaat over de Herzameling - Nederlands',
              'slug' => Str::slug('Het Traktaat over de Herzameling - Nederlands'),
              'short_description' => 'Is de mens op deze rusteloze wereld gekomen om in een waan van aards geluk een ellendig leven te leiden en vervolgens voorgoed te verdwijnen? Of schuilt er meer achter zijn bestaan dan alleen het aardse, waarin zijn menselijke potenties nooit volwaardig tot hun recht kunnen komen? Definitieve antwoorden op zulke cruciale bestaansvragen zijn te vinden in dit waardevolle werk.',
              'long_description' => '',
              'price' => 15.00,
              'is_published' => 1,
              'product_copy_id' => $nlCopy->id,
              'stock' => 100,
              'image_1' => 'images/books/herzameling/herzameling-nl-front.webp',
              'image_2' => 'images/books/herzameling/herzameling-nl-inside.webp',
              'pdf_file' => 'pdfs/herzameling.pdf',
              'online_lezen_image' => 'images/books/leesbuttons/lees_herzameling_btn.png',
              'seo_description' => '',
              'seo_tags' => ['Risale-i Nur', 'Islam', 'Geloof', "Qur'an"],
              'seo_author' => 'Said Nursi',
              'seo_robots' => 'noindex, nofollow',
              'seo_canonical_url' => '',
              'weight' => 0,
              'height' => 0,
              'width' => 0,
              'depth' => 0,
              'pages' => 0,
              'binding_type' => 'Hardcover',
              'ean_code' => '',
              'created_by' => 1,
              'updated_by' => 1,
          ],
          [
              'title' => 'Het Traktaat over de Herzameling - Engels',
              'slug' => Str::slug('Het Traktaat over de Herzameling - Engels'),
              'short_description' => 'Is de mens op deze rusteloze wereld gekomen om in een waan van aards geluk een ellendig leven te leiden en vervolgens voorgoed te verdwijnen? Of schuilt er meer achter zijn bestaan dan alleen het aardse, waarin zijn menselijke potenties nooit volwaardig tot hun recht kunnen komen? Definitieve antwoorden op zulke cruciale bestaansvragen zijn te vinden in dit waardevolle werk.',
              'long_description' => '',
              'price' => 15.00,
              'is_published' => 1,
              'product_copy_id' => $enCopy->id,
              'stock' => 100,
              'image_1' => 'images/books/herzameling/herzameling-en-front.webp',
              'image_2' => 'images/books/herzameling/herzameling-en-inside.webp',
              'seo_description' => '',
              'seo_tags' => ['Risale-i Nur', 'Islam', 'Geloof', "Qur'an"],
              'seo_author' => 'Said Nursi',
              'seo_robots' => 'noindex, nofollow',
              'seo_canonical_url' => '',
              'weight' => 0,
              'height' => 0,
              'width' => 0,
              'depth' => 0,
              'pages' => 0,
              'binding_type' => 'Hardcover',
              'ean_code' => '',
              'created_by' => 1,
              'updated_by' => 1,
          ],
          [
              'title' => 'Het Traktaat over de Herzameling - Nederlands-Turks',
              'slug' => Str::slug('Het Traktaat over de Herzameling - Nederlands-Turks'),
              'short_description' => 'Is de mens op deze rusteloze wereld gekomen om in een waan van aards geluk een ellendig leven te leiden en vervolgens voorgoed te verdwijnen? Of schuilt er meer achter zijn bestaan dan alleen het aardse, waarin zijn menselijke potenties nooit volwaardig tot hun recht kunnen komen? Definitieve antwoorden op zulke cruciale bestaansvragen zijn te vinden in dit waardevolle werk.',
              'long_description' => '',
              'price' => 20.00,
              'is_published' => 1,
              'product_copy_id' => $nlTrCopy->id,
              'stock' => 100,
              'image_1' => 'images/books/herzameling/herzameling-nl-tr-front.webp',
              'image_2' => 'images/books/herzameling/herzameling-nl-tr-inside.webp',
              'seo_description' => '',
              'seo_tags' => ['Risale-i Nur', 'Islam', 'Geloof', "Qur'an"],
              'seo_author' => 'Said Nursi',
              'seo_robots' => 'noindex, nofollow',
              'seo_canonical_url' => '',
              'weight' => 0,
              'height' => 0,
              'width' => 0,
              'depth' => 0,
              'pages' => 0,
              'binding_type' => 'Hardcover',
              'ean_code' => '',
              'created_by' => 1,
              'updated_by' => 1,
          ],
          [
              'title' => 'Het Traktaat over de Herzameling - Engels-Turks',
              'slug' => Str::slug('Het Traktaat over de Herzameling - Engels-Turks'),
              'short_description' => 'Is de mens op deze rusteloze wereld gekomen om in een waan van aards geluk een ellendig leven te leiden en vervolgens voorgoed te verdwijnen? Of schuilt er meer achter zijn bestaan dan alleen het aardse, waarin zijn menselijke potenties nooit volwaardig tot hun recht kunnen komen? Definitieve antwoorden op zulke cruciale bestaansvragen zijn te vinden in dit waardevolle werk.',
              'long_description' => '',
              'price' => 20.00,
              'is_published' => 1,
              'product_copy_id' => $enTrCopy->id,
              'stock' => 100,
              'image_1' => 'images/books/herzameling/herzameling-en-tr-front.webp',
              'image_2' => 'images/books/herzameling/herzameling-en-tr-inside.webp',
              'seo_description' => '',
              'seo_tags' => ['Risale-i Nur', 'Islam', 'Geloof', "Qur'an"],
              'seo_author' => 'Said Nursi',
              'seo_robots' => 'noindex, nofollow',
              'seo_canonical_url' => '',
              'weight' => 0,
              'height' => 0,
              'width' => 0,
              'depth' => 0,
              'pages' => 0,
              'binding_type' => 'Hardcover',
              'ean_code' => '',
              'created_by' => 1,
              'updated_by' => 1,
          ],
          [
              'title' => 'De Mirakelen van Ahmed',
              'slug' => Str::slug('De Mirakelen van Ahmed'),
              'short_description' => 'In dit boek worden er in eerste instantie de wijsheden achter de mirakelen van de profeet Mohammed verklaard. Daarna worden de verschillende varianten van zijn mirakelen beschreven. Vervolgens worden er van elke variant een aantal voorbeelden genoemd die volgens de authentiekste overleveringen absoluut hebben plaatsgevonden. Bovendien beschrijft dit boek de geestelijke persoonlijkheid van Mohammed. Iemand die dit boek begrijpend uitleest, zal niet meer in staat zijn om het profeetschap van Mohammed te verloochenen.',
              'long_description' => '',
              'price' => 10.00,
              'is_published' => 1,
              'product_copy_id' => $nlCopy->id,
              'stock' => 100,
              'image_1' => 'images/books/mirakelen/mirakelen-nl-front.webp',
              'image_2' => 'images/books/mirakelen/mirakelen-nl-inside.webp',
              'pdf_file' => 'pdfs/mirakelen.pdf',
              'online_lezen_image' => 'images/books/leesbuttons/lees_mirakelen_btn.png',
              'seo_description' => '',
              'seo_tags' => ['Risale-i Nur', 'Islam', 'Geloof', "Qur'an"],
              'seo_author' => 'Said Nursi',
              'seo_robots' => 'noindex, nofollow',
              'seo_canonical_url' => '',
              'weight' => 0,
              'height' => 0,
              'width' => 0,
              'depth' => 0,
              'pages' => 0,
              'binding_type' => 'Hardcover',
              'ean_code' => '',
              'created_by' => 1,
              'updated_by' => 1,
          ],
          [
              'title' => 'Het Traktaat over de Natuur',
              'slug' => Str::slug('Het Traktaat over de Natuur'),
              'short_description' => 'Terwijl tegenwoordig vaak de natuur wordt aangekaart om het onbestaan van een God aan te tonen, wordt er in dit boek vanuit velerlei verscheidene natuurwetenschappelijke gezichtspunten aangetoond dat het onbestaan van een Opperwezen juist onmogelijk is. Iemand die dit boek begrijpend leest, kan in geen enkel rationeel opzicht het bestaan en de eenheid van een God verloochenen.',
              'long_description' => '',
              'price' => 2.50,
              'is_published' => 1,
              'product_copy_id' => $nlCopy->id,
              'stock' => 100,
              'image_1' => 'images/books/natuur/natuur-nl-front.webp',
              'image_2' => 'images/books/natuur/natuur-nl-inside.webp',
              'pdf_file' => 'pdfs/natuur.pdf',
              'online_lezen_image' => 'images/books/leesbuttons/lees_natuur_btn.png',
              'seo_description' => '',
              'seo_tags' => ['Risale-i Nur', 'Islam', 'Geloof', "Qur'an"],
              'seo_author' => 'Said Nursi',
              'seo_robots' => 'noindex, nofollow',
              'seo_canonical_url' => '',
              'weight' => 0,
              'height' => 0,
              'width' => 0,
              'depth' => 0,
              'pages' => 0,
              'binding_type' => 'Softcover',
              'ean_code' => '',
              'created_by' => 1,
              'updated_by' => 1,
          ],
          [
              'title' => 'Het Traktaat Voor de Zieken - Nederlands',
              'slug' => Str::slug('Het Traktaat Voor de Zieken - Nederlands'),
              'short_description' => 'In dit boek worden vijfentwintig genezingen behandeld. Deze genezingen zijn als een zalf, een troost en een spiritueel recept voor zieken geschreven. Daarbij is er een condoleance in verband met het verlies van een kind, een traktaat betreffende de profeet Eyyoub en een brief aan een dokter gevoegd. Dit traktaat zal de lezer erbij helpen om alle soorten ziektes en calamiteiten te boven te komen.',
              'long_description' => '',
              'price' => 5.00,
              'is_published' => 1,
              'product_copy_id' => $nlCopy->id,
              'stock' => 100,
              'image_1' => 'images/books/zieken/zieken-nl-front.webp',
              'image_2' => 'images/books/zieken/zieken-nl-inside.webp',
              'pdf_file' => 'pdfs/zieken.pdf',
              'online_lezen_image' => 'images/books/leesbuttons/lees_zieken_btn.png',
              'seo_description' => '',
              'seo_tags' => ['Risale-i Nur', 'Islam', 'Geloof', "Qur'an"],
              'seo_author' => 'Said Nursi',
              'seo_robots' => 'noindex, nofollow',
              'seo_canonical_url' => '',
              'weight' => 170,
              'height' => 18.7,
              'width' => 11.8,
              'depth' => 1.2,
              'pages' => 0,
              'binding_type' => 'Hardcover',
              'ean_code' => '',
              'created_by' => 1,
              'updated_by' => 1,
          ],
          [
              'title' => 'Het Traktaat Voor de Zieken - Nederlands-Turks',
              'slug' => Str::slug('Het Traktaat Voor de Zieken - Nederlands-Turks'),
              'short_description' => 'In dit boek worden vijfentwintig genezingen behandeld. Deze genezingen zijn als een zalf, een troost en een spiritueel recept voor zieken geschreven. Daarbij is er een condoleance in verband met het verlies van een kind, een traktaat betreffende de profeet Eyyoub en een brief aan een dokter gevoegd. Dit traktaat zal de lezer erbij helpen om alle soorten ziektes en calamiteiten te boven te komen.',
              'long_description' => '',
              'price' => 5.00,
              'is_published' => 1,
              'product_copy_id' => $nlTrCopy->id,
              'stock' => 100,
              'image_1' => 'images/books/zieken/zieken-nl-tr-front.webp',
              'image_2' => 'images/books/zieken/zieken-nl-tr-inside.webp',
              'image_3' => 'images/books/zieken/zieken-nl-tr-shine-front.webp',
              'seo_description' => '',
              'seo_tags' => ['Risale-i Nur', 'Islam', 'Geloof', "Qur'an"],
              'seo_author' => 'Said Nursi',
              'seo_robots' => 'noindex, nofollow',
              'seo_canonical_url' => '',
              'weight' => 320,
              'height' => 18.7,
              'width' => 11.8,
              'depth' => 1.8,
              'pages' => 0,
              'binding_type' => 'Hardcover',
              'ean_code' => '',
              'created_by' => 1,
              'updated_by' => 1,
          ],
          [
              'title' => 'Het Traktaat over de Ramadan, Bezuiniging & Dankbetuiging',
              'slug' => Str::slug('Het Traktaat over de Ramadan, Bezuiniging & Dankbetuiging'),
              'short_description' => 'In dit boek worden meerdere wijsheden achter de vasten gedurende de maand Ramadan, evenals wijsheden achter bezuiniging en dankbetuiging behandeld. De bezinnende lezer zal aan de hand van dit boek de band tussen vasten, bezuinigen en dank betuigen ontwaren.',
              'long_description' => '',
              'price' => 5.00,
              'is_published' => 0,
              'product_copy_id' => $nlCopy->id,
              'stock' => 100,
              'image_1' => '',
              'image_2' => '',
              'pdf_file' => 'pdfs/ramadan.pdf',
              'online_lezen_image' => 'images/books/leesbuttons/lees_ramadan_btn.png',
              'seo_description' => '',
              'seo_tags' => ['Risale-i Nur', 'Islam', 'Geloof', "Qur'an"],
              'seo_author' => 'Said Nursi',
              'seo_robots' => 'noindex, nofollow',
              'seo_canonical_url' => '',
              'weight' => 141,
              'height' => 18,
              'width' => 11,
              'depth' => 1,
              'pages' => 0,
              'binding_type' => 'Softcover',
              'ean_code' => '',
              'created_by' => 1,
              'updated_by' => 1,
          ],

        ];

        foreach ($books as $book) {
            $book['slug'] = $book['slug'] ?? Str::slug($book['title']);
            $book['category_id'] = $category->id;
            Product::create($book);
        }

        $this->call(HerzamelingNederlandsPagesSeeder::class);
    }
}
